//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traveling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int commentID { get; set; }
        public int userCommentID { get; set; }
        public int postCommentID { get; set; }
        public string commentTitle { get; set; }
    
        public virtual post post { get; set; }
        public virtual user_s user_s { get; set; }
    }
}
