//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace traveling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userType
    {
        public int roleId { get; set; }
        public string userRole { get; set; }
        public int uid { get; set; }
    
        public virtual user user { get; set; }
    }
}
